mow_areas:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: roborock_mower
          multiple: true
    area_ids:
      required: true
      example: "[1, 2]"
      selector:
        object:
    area_names:
      required: false
      example: '["Front lawn", "Back lawn"]'
      selector:
        object:

list_areas:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: roborock_mower
          multiple: true
    map_name:
      required: false
      example: "APP_MAP1"
      selector:
        text:
