mow_areas:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: roborock_mower
          multiple: true
    area_ids:
      required: true
      example: "[1, 2]"
      selector:
        object:
    area_names:
      required: false
      example: '["Front lawn", "Back lawn"]'
      selector:
        object:

list_areas:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: roborock_mower
          multiple: true
    map_name:
      required: false
      example: "APP_MAP1"
      selector:
        text:

query:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: roborock_mower
          multiple: true
    query_type:
      required: true
      example: "GET_ROBOT_STATUS"
      selector:
        text:
    payload:
      required: false
      example: "{}"
      selector:
        object:

scan_queries:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: roborock_mower
          multiple: true
    from_app:
      required: false
      default: true
      selector:
        boolean:
    query_types:
      required: false
      example: '["GET_ROBOT_INFO", "GET_MAP_NAMES"]'
      selector:
        object:

app_strings:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: roborock_mower
          multiple: true
    contains:
      required: true
      example: '["DEFLECTION", "DIRECTION"]'
      selector:
        object:

save_map_data:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: roborock_mower
          multiple: true
    wait:
      required: false
      default: 20
      selector:
        number:
          min: 5
          max: 300
          unit_of_measurement: s
